version: '3'
services:

  app: &app
    image: ${APP_IMAGE}
    build: .
    environment:
      - EXASOL_HOST
      - EXASOL_PORT
      - EXASOL_USERNAME
      - EXASOL_PASSWORD
      - EXASOL_SCHEMA
    depends_on:
      - exasol

  dev:
    <<: *app
    volumes:
      - ./:/code
      - ./data:/data

  exasol:
    image: exasol/docker-db:latest
    privileged: true
    mem_limit: 1g
    cpus: 1

  wait:
    image: waisbrot/wait
    depends_on:
      - exasol
    environment:
      - TARGETS=exasol:8563
      - TIMEOUT=200
