version: '3'
services:

  app: &app
    image: keboola-exasol-transformation
    build: .
    platform: linux/amd64
    environment:
      - EXASOL_HOST
      - EXASOL_PORT
      - EXASOL_USERNAME
      - EXASOL_PASSWORD
      - EXASOL_SCHEMA
    depends_on:
      - exasol

  dev:
    <<: *app
    volumes:
      - ./:/code
      - ./data:/data

  exasol:
    image: exasol/docker-db:latest
    platform: linux/amd64
    privileged: true

  wait:
    image: waisbrot/wait
    depends_on:
      - exasol
    environment:
      - TARGETS=exasol:8563
      - TIMEOUT=200
