version: '3'
services:
  dev:
    build: .
    volumes:
      - ./:/code
      - ./data:/data
    environment:
      - EXASOL_HOST
      - EXASOL_PORT
      - EXASOL_USERNAME
      - EXASOL_PASSWORD
      - EXASOL_SCHEMA
