name: 'Github actions'
'on':
    push:
        branches:
            - main
            - master
        pull_request: null
env:
    APP_IMAGE: keboola-component
    KBC_DEVELOPERPORTAL_VENDOR: keboola
    KBC_DEVELOPERPORTAL_APP: keboola.exasol-transformation
    KBC_DEVELOPERPORTAL_USERNAME: keboola+exasol_transformation_gh_action
jobs:
    Push:
        runs-on: ubuntu-latest
        steps:
            -
                name: 'Check out the repo'
                uses: actions/checkout@v2
            -
                name: 'Build image'
                run: 'docker build -t ${{env.APP_IMAGE}} .'
            -
                name: 'Run tests'
                run: 'docker run ${{env.APP_IMAGE}} composer ci'
            -
                name: 'Push test image to ECR'
                uses: keboola/action-push-to-ecr@master
                with:
                    vendor: '${{env.KBC_DEVELOPERPORTAL_VENDOR}}'
                    app_id: '${{env.KBC_DEVELOPERPORTAL_APP}}'
                    username: '${{env.KBC_DEVELOPERPORTAL_USERNAME}}'
                    password: '${{secrets.KBC_DEVELOPERPORTAL_PASSWORD}}'
                    tag: test
                    push_latest: false
                    source_image: '${{env.APP_IMAGE}}'
